apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  database_url: mongo-service

#if we use namespace here then the database_url will have to be updated to mongo-service.namespace_name
#configMap must be in the cluster before it can be referenced in the mongo-express deployment
